[program:frankenphp]
process_name=%(program_name)s
command=gosu appuser frankenphp php-server --listen 0.0.0.0:8000 --root /var/www/html/public
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/workers/server.log
umask=0002
